# Generated by Django 4.2.4 on 2023-08-15 12:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.services.upload_images_service


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\d]{1,24}$', 'First letter uppercase min 2 max 24 ch')])),
            ],
            options={
                'db_table': 'car_brands',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ModelCarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\d]{1,24}$', 'First letter uppercase min 2 max 24 ch')])),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='car_model', to='cars.brandcarmodel')),
            ],
            options={
                'db_table': 'car_models',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\d]{1,24}$', 'First letter uppercase min 2 max 24 ch')])),
                ('model', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\d]{1,24}$', 'First letter uppercase min 2 max 24 ch')])),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2023)])),
                ('photo_car', models.ImageField(blank=True, upload_to=core.services.upload_images_service.upload_photo_car)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cars',
                'ordering': ('id',),
            },
        ),
    ]
